//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace mammerla.ServerIntegration
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TokenStore : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TokenStore object using the connection string found in the 'TokenStore' section of the application configuration file.
        /// </summary>
        public TokenStore() : base("name=TokenStore", "TokenStore")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TokenStore object.
        /// </summary>
        public TokenStore(string connectionString) : base(connectionString, "TokenStore")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TokenStore object.
        /// </summary>
        public TokenStore(EntityConnection connection) : base(connection, "TokenStore")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Token> Tokens
        {
            get
            {
                if ((_Tokens == null))
                {
                    _Tokens = base.CreateObjectSet<Token>("Tokens");
                }
                return _Tokens;
            }
        }
        private ObjectSet<Token> _Tokens;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tokens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTokens(Token token)
        {
            base.AddObject("Tokens", token);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mammerla.ServerIntegration", Name="Token")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Token : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Token object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="storeTypeId">Initial value of the StoreTypeId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="tokenContent">Initial value of the TokenContent property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Token CreateToken(global::System.Guid id, global::System.Byte storeTypeId, global::System.String userId, global::System.String tokenContent, global::System.Int32 type)
        {
            Token token = new Token();
            token.Id = id;
            token.StoreTypeId = storeTypeId;
            token.UserId = userId;
            token.TokenContent = tokenContent;
            token.Type = type;
            return token;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte StoreTypeId
        {
            get
            {
                return _StoreTypeId;
            }
            set
            {
                OnStoreTypeIdChanging(value);
                ReportPropertyChanging("StoreTypeId");
                _StoreTypeId = StructuralObject.SetValidValue(value, "StoreTypeId");
                ReportPropertyChanged("StoreTypeId");
                OnStoreTypeIdChanged();
            }
        }
        private global::System.Byte _StoreTypeId;
        partial void OnStoreTypeIdChanging(global::System.Byte value);
        partial void OnStoreTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TokenContent
        {
            get
            {
                return _TokenContent;
            }
            set
            {
                OnTokenContentChanging(value);
                ReportPropertyChanging("TokenContent");
                _TokenContent = StructuralObject.SetValidValue(value, false, "TokenContent");
                ReportPropertyChanged("TokenContent");
                OnTokenContentChanged();
            }
        }
        private global::System.String _TokenContent;
        partial void OnTokenContentChanging(global::System.String value);
        partial void OnTokenContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Secret
        {
            get
            {
                return _Secret;
            }
            set
            {
                OnSecretChanging(value);
                ReportPropertyChanging("Secret");
                _Secret = StructuralObject.SetValidValue(value, true, "Secret");
                ReportPropertyChanged("Secret");
                OnSecretChanged();
            }
        }
        private global::System.String _Secret;
        partial void OnSecretChanging(global::System.String value);
        partial void OnSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContextContent
        {
            get
            {
                return _ContextContent;
            }
            set
            {
                OnContextContentChanging(value);
                ReportPropertyChanging("ContextContent");
                _ContextContent = StructuralObject.SetValidValue(value, true, "ContextContent");
                ReportPropertyChanged("ContextContent");
                OnContextContentChanged();
            }
        }
        private global::System.String _ContextContent;
        partial void OnContextContentChanging(global::System.String value);
        partial void OnContextContentChanged();

        #endregion

    }

    #endregion

}
